ALTER TABLE `EmailRecipient` MODIFY `status` ENUM('PENDING', 'QUEUED', 'SENDING', 'DISPATCHING', 'SENT', 'FAILED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE `EmailEvent` MODIFY `status` ENUM('PENDING', 'QUEUED', 'SENDING', 'DISPATCHING', 'SENT', 'FAILED') NOT NULL;
